graphql:
  servlet:
    mapping: /graphql
    enabled: true
#    corsEnabled: true
#    cors:
#      allowed-origins: http://some.domain.com
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION

  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
#    introspection-enabled: true

### begin graphql
  playground:
    mapping: /playground
#    endpoint: /graphql
#    subscriptionEndpoint: /subscriptions
#    staticPath.base: my-playground-resources-folder
#    enabled: true
    pageTitle: GraphQL Playground
### end graphql